### ISSUE TITLE
Where can I find your results?

### ISSUE THREAD

**Issue by MohammadVahidiPro** [perceptiveshawty/RankCSE#1]
Hi, I wanted to thank you for your immense contributions to the community, and ask if were you able to reproduce the results reported in the paper? Could your share your results? thank you again for your help.  

best regards

**Comment by perceptiveshawty** [comment]
I wasn't able to reproduce the results from the paper, but IIRC they are close enough (I think within 1%). You can run the evaluation script and pass one of the [pre-trained models](https://github.com/perceptiveshawty/RankCSE#pretrained-models) as the path to see the exact results.

**Comment by MohammadVahidiPro** [comment]
> I wasn't able to reproduce the results from the paper, but IIRC they are close enough (I think within 1%). You can run the evaluation script and pass one of the [pre-trained models](https://github.com/perceptiveshawty/RankCSE#pretrained-models) as the path to see the exact results. 

close enough, thanks for your help
